### ISSUE TITLE
CORS 문제 발생

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#33]
## 💡Description

다음과 같은 CORS 문제가 발생합니다.
Access to XMLHttpRequest at 'https://calmiary-be.org/post/write' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by minjeongss** [comment]
프론트에서 proxy 설정 후, 뜬 에러입니다.

Access to XMLHttpRequest at 'https://calmiary-be.org/post/write' (redirected from 'http://localhost:5173/api/post/write') from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by minjeongss** [comment]
프론트에서 설정한 proxy는 다음과 같습니다.
```
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      '/api': {
        target: 'https://calmiary-be.org',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
});

```

**Comment by minjeongss** [comment]
시도한 것
- 프론트에서 proxy 설정X + 서버 직접적인 주소
- 프론트에 proxy 설정O + 서버 직접적인 주소
- 프론트에서 proxy 설정O + /api

모두 실패했습니다 😭

**Comment by minjeongss** [comment]
문제가 되는 원인의 코드입니다.

```
  const mutation = useMutation({
    mutationFn: (newContent: WriteData) => {
      return axios.post('/api/post/write', newContent);
    },
    onSuccess: async () => {
      console.log('success');
    },
    onError: async () => {
      console.log('fail');
    },
  });
```

**Comment by ruehan** [comment]
@minjeongss 
일단 수정은 해봤는데 테스트 부탁드려요! 이번에 안되면 제가 조금 더 테스트 해보겠습니다...
아 맞다. https로 부탁드려요 ㅋㅋㅋ

**Comment by minjeongss** [comment]
@ruehan 실패..했습니다..😭

- proxy 설정 O + /api로 테스트
- proxy 설정 X + https 주소로 테스트

위의 두 개를 테스트했습니다..

**Comment by minjeongss** [comment]
@ruehan 성공했습니다!!!!!!!!!!!
따로 바꾼건 없어요...
proxy 설정 + /api로 테스트했고, db dashboard에 들어간 것 확인했습니다!

**Comment by ruehan** [comment]
@minjeongss 제가 이것저것 바꾼거 같긴 해요(?) 아무튼 다행입니다 ㅋㅋㅋ

**Comment by minjeongss** [comment]
@ruehan 감사합니다 ㅠ.ㅠ!!! 마음 가벼운 주말 보내시길 ㅎㅎ
