### ISSUE TITLE
글쓰기 AI 답변 형태 통일

### ISSUE THREAD

**Issue by minjeongss** [prgrms-fe-devcourse/NFE1-1-3-Calmiary#42]
## 💡Description
글쓰기를 진행한 후, 돌아오는 AI 답변의 형태가 일정하지 않아서, 어떤 답변이 돌아오는지 예측하기 어려움을 발견했습니다!
혹시 답변이 돌아오는 형태가 생성형AI에서 임시로 던져주는 형태인가요? 😢

AI 답변의 형태는 두 가지로 분리된다고 분석했습니다.

1. 앞에 여백이 많고, *가 존재하지 않는 경우
```
                  물론이죠! 언제든지 걱정이 있으면 나눠주세요. 누구나 힘든 날이 있고, 그렇게 느끼는 것은 전혀 이상한 일이 아니에요. 당신의 마음과 감정을 이해하는 사람이 있다는 걸 잊지 마세요.

 걱정을 조금 덜어낼 수 있는 방법을 찾아보는 것도 좋을 것 같아요. 예를 들어, 짧은 산책이나 좋아하는 음악을 듣는 것이 도움이 될 수 있어요. 또는 하루의 끝에서, 힘든 감정들을 정리해보는 시간을 가져보는 것도 좋답니다.
```
2. 앞에 여백이 많고, *가 존재하는 경우
```
                  ** 좋은 아침이에요! 오늘 하루가 조금 걱정스러웠나 보군요. 그런 기분이 드는 건 누구에게나 있을 수 있는 일이에요. 당신은 소중한 존재이고, 이 모든 감정을 겪고 있다는 것만으로도 정말 용감한 거예요. 힘내세요!

**

 ** 걱정을 좀 덜기 위해 오늘 하루, 짧은 시간이라도 자신을 위한 시간을 가져보는 건 어떨까요? 좋아하는 음악을 듣거나, 산책을 하면서 마음을 가라앉히는 것도 좋은 방법이에요. 자연과 함께하는 시간은 마음의 부담을 덜어줄 수 있어요!
```

**Comment by minjeongss** [comment]
생성형 AI에서 임시로 답변의 형태를 제공한다면, 제가 *를 찾아서 제거하는 형태로 코드 구현 진행하겠습니다! 😄

**Comment by ruehan** [comment]
@minjeongss 
일단 코드를 한번 확인해봤는데 제가 확인한 바는 아래와 같습니다..!

### 1. 대시보드에서 확인 시에 여백이 생기는 경우
<img width="1657" alt="image" src="https://github.com/user-attachments/assets/380471f0-ddc1-46d0-859d-fa472fdf8895">
<img width="797" alt="image" src="https://github.com/user-attachments/assets/a0b73b7c-7bc3-448a-be2b-12a3c9f3bad7">

첫번째 사진이 서버에서 확인한 AI 답변이고 두번째 사진이 대시보드에서 확인한 부분인데 서버 부분에서는 여백이 생기지 않는 걸 확인했습니다.

프론트 부분에서 데이터를 받을 때 여백이 생기는지를 확인해봐야 할 것 같습니다.

### 2. 답변에 *가 포함되는 경우

이 부분은 서버 부분에서 처리를 해뒀습니다!

**Comment by minjeongss** [comment]
프론트에서 데이터 받을 때, 여백이 생기지 않음을 확인했습니다! 🫡👍👍👍
답변에 *도 포함되지 않음을 확인했어요!! 감사합니다!! 😊

- 예시
```
"갑자기 서버 연결 문제가 생기면 정말 불안하고 걱정되실 거예요. 이럴 때는 누구나 당황할 수 있는데, 괜찮아요. 여러 사람들이 비슷한 경험을 하니까요. 감정을 이해해줄 사람이 있다는 걸 잊지 마세요.

  우선 서버 로그를 확인해서 어떤 오류가 발생했는지 살펴보세요. 그 이후에 인터넷 연결 상태나 서버 상태를 점검해보는 것도 좋습니다. 필요한 경우 기술 지원 팀에 문의하는 것도 고려해보세요. 문제가 해결되기를 응원할게요!"
```
